# Config file

version: 1
markerset.name: 土地表示
markerset.check-interval: 300
marker.description: "\
  %1の土地 ( %0 )<br><br>\
  名前: %0<br>\
  所有者: %1<br>\
  範囲: (x: %2 ～ %5, y: %3 ～ %6, z: %4 ～ %7, %8)"
marker.colors:
  - "f44336"
  - "E91E63"
  - "9C27B0"
  - "673AB7"
  - "3F51B5"
  - "2196F3"
  - "03A9F4"
  - "00BCD4"
  - "009688"
  - "4CAF50"
  - "8BC34A"
  - "CDDC39"
  - "FFEB3B"
  - "FFC107"
  - "FF9800"
  - "FF5722"
  - "795548"
  - "9E9E9E"
  - "607D8B"